### ISSUE TITLE
Tensorflow 2.16.1 compatibility

### ISSUE THREAD

**Issue by Stikus** [KarchinLab/mhcnuggets#38]
Hello, as you can see in pVACtools issue https://github.com/griffithlab/pVACtools/issues/1084 - https://github.com/openvax/mhcflurry and mhcnuggets doesn't work with latest [2.16.1 version of tensorflow](https://github.com/tensorflow/tensorflow/releases/tag/v2.16.1).

```
Exception: An error occurred while calling MHCnuggets:
/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/masking.py:47: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pvactools/lib/call_mhcnuggets.py", line 84, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/pvactools/lib/call_mhcnuggets.py", line 61, in main
    predict(args.class_type, tmp_file.name, mhcnuggets_allele(args.allele, args.class_type), output=tmp_output_file.name, rank_output=True)
  File "/usr/local/lib/python3.10/dist-packages/mhcnuggets/src/predict.py", line 93, in predict
    model.compile(loss='mse', optimizer=Adam(lr=0.001))
  File "/usr/local/lib/python3.10/dist-packages/keras/src/optimizers/adam.py", line 60, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/keras/src/backend/tensorflow/optimizer.py", line 19, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/keras/src/optimizers/base_optimizer.py", line 38, in __init__
    raise ValueError(f"Argument(s) not recognized: {kwargs}")
ValueError: Argument(s) not recognized: {'lr': 0.001}
```

Looks like some legacy code stopped working:
https://github.com/KarchinLab/mhcnuggets/blob/master/mhcnuggets/src/predict.py#L90-L93

Maybe tensorflow version should be pinned until code is fixed?

Similar https://github.com/openvax/mhcflurry/issues/234 issue.

**Comment by indapa** [comment]
I was facing the same issue.  Should I install another version of TensorFlow?

**Comment by KoppGergely** [comment]
Hi, I encountered the same issue, and was able to work around it, without using an older version of TensorFlow, based on the advice here: https://stackoverflow.com/questions/78197496/value-error-problem-i-encountered-with-tensorflow-optimizer-parameter

Essentially, you have to change the 'lr' to 'learning_rate' in the python scripts. I have not tested this solution thoroughly, but this has worked for me for simple cases. 

Example: in scr/predict.py change line 93 from:
`#  model.compile(loss='mse', optimizer=Adam(lr=0.001))` 
to 
 ` model.compile(loss='mse', optimizer=Adam(learning_rate=0.001)) `

**Comment by Alexandra2022kzn** [comment]
Thank you for this tool! I see you've already fixed the problem with tensorflow. Could you please make a new release version?
